[package]
name = "ark-accumulation"
version = "0.1.0"
authors = [
  "Benedikt Bünz <benedikt@cs.stanford.edu>",
  "Alessandro Chiesa <alexch@berkeley.edu>",
  "William Lin <will.lin@berkeley.edu>",
  "Pratyush Mishra <pratyush@berkeley.edu>",
  "Nicholas Spooner <nick.spooner@berkeley.edu>",
]
edition = "2018"

[dependencies]
ark-ff = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-poly-commit = { git = "https://github.com/Will-Lin4/poly-commit/", branch = "accumulation-experimental", default-features = false }
ark-sponge = { path = "../sponge", default-features = false }
ark-std = { git = "https://github.com/arkworks-rs/utils", default-features = false }
derivative = { version = "2.1.1", features = [ "use_core" ] }
digest = "0.9.0"
rand_core = { version = "0.5", default-features = false }

# Dependencies for r1cs
ark-crypto-primitives = { git = "https://github.com/arkworks-rs/crypto-primitives.git", branch = "main", default-features = false, optional = true }
ark-ec = { git = "https://github.com/arkworks-rs/algebra", default-features = false, optional = true }
ark-marlin = { path = "../marlin", default-features = false, features = [ "density-optimized" ], optional = true }
ark-nonnative-field = { git = "https://github.com/arkworks-rs/nonnative", default-features = false, optional = true }
ark-relations = { git = "https://github.com/arkworks-rs/snark", default-features = false, optional = true }
ark-r1cs-std = { git = "https://github.com/arkworks-rs/r1cs-std", default-features = false, optional = true }

[dev-dependencies]
ark-ec = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-ed-on-bls12-381 = { git = "https://github.com/arkworks-rs/curves", default-features = false }
ark-poly = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
rand = { version = "0.7.3", default-features = false }
sha2 = { version = "0.9.1", default_features = false }

[features]
default = [ "r1cs", "std", ]
parallel = [ "std", "ark-ff/parallel", "ark-poly/parallel", "ark-poly-commit/parallel", "ark-std/parallel" ]
r1cs = [ "ark-crypto-primitives/r1cs", "ark-ec", "ark-ed-on-bls12-381/r1cs", "ark-marlin", "ark-nonnative-field", "ark-relations", "ark-r1cs-std", "ark-sponge/r1cs" ]
std = [ "ark-ff/std", "ark-poly-commit/std", "ark-std/std" ]
