[package]
name = "ark-accumulation"
version = "0.1.0"
authors = [
  "Benedikt Bünz <benedikt@cs.stanford.edu>",
  "Alessandro Chiesa <alexch@berkeley.edu>",
  "William Lin <will.lin@berkeley.edu>",
  "Pratyush Mishra <pratyush@berkeley.edu>",
  "Nicholas Spooner <nick.spooner@berkeley.edu>",
]
edition = "2018"

[dependencies]
ark-ec = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-ff = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-poly-commit = { git = "https://github.com/Will-Lin4/poly-commit", branch = "accumulation-experimental", default-features = false }
ark-sponge = { git = "https://github.com/arkworks-rs/sponge/", branch = "experimental", default-features = false }
ark-std = { git = "https://github.com/arkworks-rs/utils", default-features = false }
derivative = { version = "2.1.1", features = [ "use_core" ] }
digest = "0.9.0"
rand_core = { version = "0.5", default-features = false }
rayon = { version = "1", optional = true }

[dev-dependencies]
ark-poly = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-ed-on-bls12-381 = { git = "https://github.com/arkworks-rs/curves", default-features = false }
sha2 = { version = "0.9.1", default_features = false}
rand = { version = "0.8", default-features = false }
rand_chacha = { version = "0.2.1", default-features = false }

[features]
default = ["std", "parallel"]
std = [ "ark-ff/std", "ark-poly-commit/std", "ark-std/std" ]
parallel = [ "std", "ark-ec/parallel", "ark-ff/parallel", "ark-poly/parallel", "ark-poly-commit/parallel", "ark-std/parallel", "rayon" ]

