[package]
name = "ark-accumulation"
version = "0.1.0"
authors = [
  "Benedikt Bünz <benedikt@cs.stanford.edu>",
  "Alessandro Chiesa <alexch@berkeley.edu>",
  "William Lin <will.lin@berkeley.edu>",
  "Pratyush Mishra <pratyush@berkeley.edu>",
  "Nicholas Spooner <nick.spooner@berkeley.edu>",
]
edition = "2018"

[dependencies]
ark-std = { git = "https://github.com/arkworks-rs/utils", default-features = false }
derivative = { version = "2.1.1", features = [ "use_core" ] }
rand_core = { version = "0.5", default-features = false }

[dev-dependencies]
ark-ff = { git = "https://github.com/arkworks-rs/algebra", default-features = false}

[features]
default = ["std"]
std = []
