[package]
name = "ark-accumulation"
version = "0.1.0"
authors = [
  "Benedikt Bünz <benedikt@cs.stanford.edu>",
  "Alessandro Chiesa <alexch@berkeley.edu>",
  "William Lin <will.lin@berkeley.edu>",
  "Pratyush Mishra <pratyush@berkeley.edu>",
  "Nicholas Spooner <nick.spooner@berkeley.edu>",
]
edition = "2018"

[dependencies]
ark-ec = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-ff = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-poly-commit = { git = "https://github.com/scipr-lab/poly-commit/", default-features = false }
ark-sponge = { path = "../sponge" }
ark-std = { git = "https://github.com/arkworks-rs/utils", default-features = false }
derivative = { version = "2.1.1", features = [ "use_core" ] }
digest = "0.9"
rand_core = { version = "0.5", default-features = false }

[dev-dependencies]
ark-bls12-381 = { git = "https://github.com/arkworks-rs/curves" }
sha2 = { version = "0.9.2", default-features = false }
rand = { version = "0.7", default-features = false }

[features]
default = ["std"]
std = []
