[package]
name = "ark-accumulation"
version = "0.1.0"
authors = [
  "William Lin <will.lin@berkeley.edu>"
]
edition = "2018"

[dependencies]
rand_core = { version = "0.5", default-features = false }

[dev-dependencies]
algebra-core = { git = "https://github.com/scipr-lab/zexe/", default-features = false}

